sudo: required
services:
  - docker

before_install:
  - docker build -t vitor96k/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vitor96k/client-test npm run test

after_success:
  - docker build -t vitor96k/complex-client ./client
  - docker build -t vitor96k/complex-nginx ./nginx
  - docker build -t vitor96k/complex-server ./server
  - docker build -t vitor96k/complex-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push vitor96k/complex-client
  - docker push vitor96k/complex-nginx
  - docker push vitor96k/complex-server
  - docker push vitor96k/complex-worker

deploy:
  provider: elasticbeanstalk
  region: 'sa-east-1'
  app: 'complex'
  env: 'Complex-env'
  bucket_name: 'elasticbeanstalk-sa-east-1-502646121377'
  bucket_path: 'complex'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY